swagger: '2.0'
info:
  title: btools API
  version: "0.1"
  description:  btools API for finding the most similar tools to a user's text input
consumes:
  - application/json
produces:
  - application/json
paths:
  /searchtool:
    get:
      operationId: simtools.get_sim
      summary: Find the most similar tools
      parameters:
        - name: tool_text
          in: query
          type: string
          required: true
      responses:
        200:
          description: similar tools as pmids
          schema:
            type: array
            items:
              type: string